[platformio]
default_envs = waveshare-prototype
src_dir = src
lib_dir = lib
test_dir = test

[env:waveshare-prototype]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_upload.maximum_size = 6291456
board_build.partitions = partitions.csv
board_build.arduino.memory_type = qio_opi
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DLV_CONF_PATH=ClockLvglConfig.h
  -I../waveshare-hodiny/WaveshareHodiny
lib_deps =
  lvgl/lvgl@8.3.10
  bblanchon/ArduinoJson@7.1.0

[env:native]
platform = native
build_flags =
  -std=gnu++17
  -Ilib/app_core/include
test_build_src = no
