[platformio]
default_envs = waveshare-multi-mode
src_dir = src
lib_dir = lib
test_dir = test

[env:waveshare-multi-mode]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_upload.maximum_size = 6291456
board_build.partitions = partitions.csv
board_build.arduino.memory_type = qio_opi
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DLV_CONF_PATH=ClockLvglConfig.h
  -I../waveshare-hodiny/WaveshareHodiny
  -I../MeteoPlaneRadar/MeteoPlaneRadar
lib_deps =
  lvgl/lvgl@8.3.10
  bblanchon/ArduinoJson@7.1.0
  moononournation/GFX Library for Arduino@1.6.6
  bitbank2/PNGdec@1.0.1

[env:native]
platform = native
build_flags =
  -std=gnu++17
  -Ilib/app_core/include
  -I../waveshare-hodiny/WaveshareHodiny
test_build_src = no
